<?php

namespace Tests\Feature\Cms\tests\UploadAssets;

use Anacreation\Cms\Enums\AdminPermissionAction;
use Anacreation\Cms\Models\Language;
use Anacreation\Cms\Tests\TestCase;
use Anacreation\MultiAuth\Model\Admin;
use Anacreation\MultiAuth\Model\AdminPermission;
use Anacreation\MultiAuth\Model\AdminRole;
use Illuminate\Foundation\Testing\RefreshDatabase;

class UploadDefinitionTest extends TestCase
{
    use RefreshDatabase;

    private $admin;
    private $role;

    public function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
        factory(Language::class)->create([
            'is_default' => true
        ]);

        $this->admin = factory(Admin::class)->create();

        $this->role = factory(AdminRole::class)->create();

        $this->admin->roles()->save($this->role);
    }

    /**
     * @test
     */
    public function show_upload_definition_link_in_menu() {

        $this->withoutExceptionHandling();
        collect([
            "upload_definition",
            AdminPermissionAction::Index()->getValue() . "_definition",
            AdminPermissionAction::Create()->getValue() . "_definition",
        ])->each(function ($permissionCode) {
            $permission = new AdminPermission();
            $permission->label = $permissionCode;
            $permission->code = $permissionCode;
            $permission->save();
            $this->role->permissions()->attach($permission->id);
        });

        $this->actingAs($this->admin, 'admin');

        $uri = url("admin/designs");

        $response = $this->get($uri);

        $response->assertSee('Upload Definition')
                 ->assertSee(route('designs.upload.definition'));

    }

    /**
     * @test
     */
    public function visit_upload_definition() {
        $this->withoutExceptionHandling();
        collect(["upload_definition"])->each(function ($permissionCode) {
            $permission = new AdminPermission();
            $permission->label = $permissionCode;
            $permission->code = $permissionCode;
            $permission->save();
            $this->role->permissions()->attach($permission->id);
        });
        $this->actingAs($this->admin, 'admin');

        $uri = route('designs.upload.definition');

        $this->get($uri)
             ->assertSuccessful()
             ->assertViewIs("cms::admin.designs.upload.definition")
             ->assertSee("Upload Definition");
    }
}

