/**
 * Created by Xavier on 31/1/2018.
 */
export const CONTENT_DELETED = 'CONTENT_DELETED'
export const CONTENT_GET_DIRTY = 'CONTENT_GET_DIRTY'
export const CONTENT_GET_CLEAN = 'CONTENT_GET_CLEAN'
export const UPLOAD_PROGRESS = 'UPLOAD_PROGRESS'
export const UPLOAD_START = 'UPLOAD_START'