<?php

namespace Anacreation\Cms\Tests\Feature\Route;

use Anacreation\Cms\Models\Language;
use Anacreation\Cms\Models\Page;
use Anacreation\Cms\Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class CustomRedirectTest extends TestCase
{
    use RefreshDatabase;


    public function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
        factory(Language::class)->create([
                                             'is_default' => true,
                                         ]);
    }

    /**
     * @test
     */
    public function redirect_not_found_page() {

        factory(Page::class)->create([
                                         'uri'       => 'dummy2',
                                         'is_active' => true,
                                         'template'  => 'home',
                                     ]);

        config(['cms.custom_redirect' => ['/dummy1' => '/dummy2']]);

        $this->withoutExceptionHandling();

        $this->get('/dummy1')
             ->assertRedirect('/dummy2');

    }
}
